In [15]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv('data/input_day1_1.txt', header=None)

In [26]:
values = data[0].values

In [27]:
summed = np.array([[i + j for j in data[0].values] for i in values])

In [28]:
loc = np.where(summed == 2020)

In [29]:
result = values[loc[0][0]] * values[loc[1][0]]

In [30]:
result

838624

In [31]:
summed = np.array([[[i + j + k for k in values] for j in values] for i in values])

In [32]:
loc = np.where(summed == 2020)

In [38]:
result = values[loc[0][0]] * values[loc[1][0]] * values[loc[2][0]]

In [39]:
result

52764180

In [37]:
loc

(array([ 43,  43,  86,  86, 156, 156]),
 array([ 86, 156,  43, 156,  43,  86]),
 array([156,  86, 156,  43,  86,  43]))